DIT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ingenieria.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += [
#     path('', RedirectView.as_view(url='/app/', permanent=True)),
# ]


#  Add Django site authentication urls (for login, logout, password management)
# urlpatterns += [
#     path('cuentas/', include('django.contrib.auth.urls')),
# ]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ingenieria/models.py
from __future__ import unicode_literals
from django.db import models
# from django.contrib.auth.models import AbstractUser
# from django.contrib.auth.models import User
# from django.dispatch import receiver
# from django.db.models.signals import post_save
from django.urls import reverse
import uuid
from django.contrib.auth.models import User

from django.utils import timezone


class ClaseModelo(models.Model):
    activo = models.BooleanField(
        default=True, null=True, editable=True)

    creado = models.DateTimeField(
        auto_now_add=True, null=True, editable=True)
    modificado = models.DateTimeField(
        default=timezone.now, null=True, editable=True)

    class Meta:
        abstract = True


class Recurrente(ClaseModelo):
    nombre = models.CharField(max_length=50, unique=True)
    apellido = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    telefono = models.IntegerField(null=True, blank=True)
    ruc = models.IntegerField(null=True, blank=True)
    rmc = models.IntegerField(null=True, blank=True)

    def __str__(self):
        if self.apellido:
            return '%s, %s' % (self.nombre, self.apellido)
        else:
            return self.nombre

    class Meta:
        ordering = ["-nombre"]


class Barrio(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["nombre"]


class Calle(models.Model):
    #  TIPO
    EMPEDRADA = 1
    ASFALTADA = 2
    INDETERMINADA = 3
    TIPO_CHOICES = (
        (EMPEDRADA, "Empedrada"),
        (ASFALTADA, "Asfaltada"),
        (INDETERMINADA, "Indeterminada"),)

    #  SENTIDO
    UNICO = 1
    DOBLE = 2
    INDETERMINADO = 3
    SENTIDO_CHOICES = (
        (UNICO, "Unico"),
        (DOBLE, "Doble"),
        (INDETERMINADO, "Indeterminado"),)

    #  NUMERACION
    DERECHA = 1
    IZQUIERDA = 2
    INDETERMINADA = 3
    NUMERACION_CHOICES = (
        (DERECHA, "Derecha"),
        (IZQUIERDA, "Izquierda"),
        (INDETERMINADA, "Indeterminada"),)

    nombre = models.CharField(max_length=50)
    tipo = models.IntegerField(choices=TIPO_CHOICES, null=True, default=2)
    sentido = models.IntegerField(choices=SENTIDO_CHOICES, null=True, blank=True)
    numeracion = models.IntegerField(choices=NUMERACION_CHOICES,
        help_text='Lado numeración viviendas', null=True, blank=True)
    barrio = models.ForeignKey(Barrio, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["nombre"]


class Documento_estado(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Documento_referencia(ClaseModelo):
    nombre = models.CharField(max_length=50)
    detalle = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["-nombre"]


class Documento(ClaseModelo):
    #  SENTIDO
    UNICO = 1
    DOBLE = 2
    SENTIDO_CHOICES = (
        (UNICO, "Unico"),
        (DOBLE, "Doble"),)

    #  CALZADA
    DERECHA = 1
    IZQUIERDA = 2
    CALZADA_CHOICES = (
        (DERECHA, "Derecha"),
        (IZQUIERDA, "Izquierda"),)

    #  CLASE
    EXPEDIENTE = 1
    NOTA = 2
    MEMO = 3
    OFICIO = 4
    FORMULARIO = 5
    CLASE_CHOICES = (
        (EXPEDIENTE, "Expediente"),
        (NOTA, "Nota"),
        (MEMO, "Memo"),
        (OFICIO, "Oficio"),
        (FORMULARIO, "Formulario"),)

    creado_por = models.ForeignKey(
        User, related_name='generado_por', on_delete=models.SET_NULL,
        null=True, blank=True)

    tipo = models.IntegerField(choices=CLASE_CHOICES, default=1)
    nro = models.IntegerField(blank=True, null=True)
    fecha = models.DateField()
    recurrente = models.ForeignKey(Recurrente, null=True, on_delete=models.SET_NULL)
    mesa = models.ForeignKey(
        User, related_name="creado_por", null=True, on_delete=models.SET_NULL, blank=True)
    tecnico = models.ForeignKey(
        User, related_name="asignado_a", null=True, on_delete=models.SET_NULL, blank=True)

    motivo = models.ManyToManyField(
        Documento_referencia, related_name='motivo')
    # , through='Motivo_detalle'

    # calle_principal = models.ForeignKey(
    #     Calle, on_delete=models.CASCADE,
    #     related_name="calle_principal", null=True, blank=True)
    # calzada = models.IntegerField(choices=CALZADA_CHOICES, null=True, blank=True)
    # calle1 = models.ForeignKey(
    #     Calle, on_delete=models.CASCADE, related_name="calle1", null=True, blank=True)
    # calle2 = models.ForeignKey(
    #     Calle, on_delete=models.CASCADE, related_name="calle2", null=True, blank=True)
    # inicio_evento = models.DateTimeField(null=True, blank=True)
    # fin_evento = models.DateTimeField(null=True, blank=True)
    estado = models.ForeignKey(Documento_estado, on_delete=models.CASCADE)
    observacion = models.TextField(help_text='Descripción adicional', null=True, blank=True)
    imagen = models.ImageField(null=True, blank=True)

    def dias(self):
        return self.fecha >= timezone.now() - datetime.timedelta(days=15)
    #  upload_to="/images/"

    # def display_motivo(self):
    #     return ', '.join(
    #         [Documento_motivo.name for Documento_motivo
    #         in self.Documento_motivo.all()[:3]])

    # display_motivo.short_description = 'Motivo'

    @property
    def solo_año(self):
        return self.fecha.strftime('%Y')

    def __str__(self):
        return '%d/%s' % (self.nro, self.solo_año)
        # return '%s, %s' % (self.nro, self.recurrente)

    def get_absolute_url(self):
        return reverse('documento-detalle', args=[str(self.id)])

    class Meta:
        ordering = ["-nro"]
        unique_together = (("nro", "fecha"),)


class DocumentoInstance(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4,
        help_text="ID único para Documento")
    documento = models.ForeignKey(
        'Documento', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return '%s (%s)' % (self.id, self.documento.nro)


class Destino(ClaseModelo):
    nombre = models.CharField(max_length=50, unique=True)
    acronimo = models.CharField(
        max_length=15, unique=True, null=True, blank=True)

    class Meta:
        ordering = ['nombre']
        unique_together = (('nombre', 'acronimo'))


class Documento_mesa(models.Model):
    documento = models.ForeignKey(
        Documento, on_delete=models.CASCADE, null=True)
    tecnico = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mesa = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='mesa', null=True)
    destino = models.ForeignKey(
        Destino, on_delete=models.SET_NULL, null=True, blank=True)
    para = models.ForeignKey(
        Destino, related_name='destino_2', on_delete=models.SET_NULL, null=True, blank=True)
    fecha_entrada = models.DateField()
    fecha_salida = models.DateField()
    fecha_registro_mesa = models.DateTimeField(auto_now_add=True)

    recibido = models.BooleanField(default=False)
    fecha_recibido = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.documento

    class Meta:
        ordering = ["-fecha_salida"]


class Evento_tipo(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["-nombre"]


class Cierre_tipo(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["-nombre"]


class Camiones_tipo(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["-nombre"]


class Herramientas_tipo(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["-nombre"]


class Suelo_tipo(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["-nombre"]


class Cartel(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.CharField(max_length=50, null=True)


class Informe_clase(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["-nombre"]


class InformeResultado(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.nombre

class Informe(ClaseModelo):
    # Informe.objects.filter(tipo__nombre="Espacio Reservado").count()
    documento = models.ForeignKey(
        Documento, on_delete=models.CASCADE, null=True)
    DERECHA = 1
    IZQUIERDA = 2
    CALZADA_CHOICES = (
        (DERECHA, "Derecha"),
        (IZQUIERDA, "Izquierda"),)
    nro = models.IntegerField()
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    recurrente = models.ForeignKey(
        Recurrente, on_delete=models.CASCADE, null=True)
    resultado = models.ForeignKey(
        InformeResultado, on_delete=models.CASCADE, null=True)

    tipo = models.ManyToManyField(Informe_clase, related_name='clase')
    espacios = models.IntegerField(null=True, blank=True)

    # DIRECCION ---------------------------
    calle_principal = models.ForeignKey(
        Calle, on_delete=models.CASCADE,
        related_name="inf_calle_principal", null=True, blank=True)

templates/documento_delete.html
{% extends 'base.html' %}

{% block content %}
                  <div class="col-md-6">
                    <div class="card border-left-danger shadow h-100 py-2">
                      <div class="card-body">
                       
                        <div class="row no-gutters align-items-center">
                          <div class="col mr-2">
                            <div class="text-xl font-weight-bold text-danger text-uppercase mb-2">ELIMINAR DOCUMENTO</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                             {% if obj.tipo == 1 %}
									Expediente Nro: {{obj.nro}} <br>
									{% elif obj.tipo == 2 %}
									Nota Nro: {{obj.nro}} <br>
									{% elif obj.tipo == 3 %}
									Memo Nro: {{obj.nro}} <br>
									{% elif obj.tipo == 4 %}
									Oficio Nro: {{obj.nro}} <br>
									{% elif obj.tipo == 5 %}
									Formulario <br>
								{% endif %}
							</div>
                             Recurrente: {{obj.recurrente.nombre}} <br>
                             Fecha: {{obj.fecha|date:"d/m/Y"}} <br>
                             Motivos: {{obj.motivo.all|join:", " }} <br>
                             <br>
                            
                          </div>
                          <br>
                        </div>

						<div class="row no-gutters align-items-center">
							<form method="POST">
								{% csrf_token %}
								<button type="submit" class="btn btn-danger">
									<i class="fas fa-trash"></i> Eliminar</button>
								<a href=" {% url 'documento_list' %} " class="btn btn-secondary">
									<i class="fas fa-undo"></i> Volver</a>
							</form>
						</div>
                      </div>							
                    </div>
                  </div>
{% endblock %}

templates/documento_form.html
{% extends 'base.html' %}


{% block content %}
	{% if form.errors %}
		<div class="alert alert-warning" role="alert">
			<h5>Favor observar lo siguiente:</h5>
		  {{ form.errors }}
		</div>
	{% endif %}

	<form method="post" class="form-horizontal" enctype="multipart/form-data">	  	
	  	{% csrf_token %} 
			<!-- {# {{ form.as_p }} #} -->
		<div class="card shadow mb-4">
            <div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">REGISTRAR/MODIFICAR DOCUMENTO</h6>
            </div>

		<div class="card-body">

					<div class="form-row">
						<div class="form-group col-md-4">
							<label for="{{form.tipo.label}}"><strong>{{form.tipo.label}}</strong></label>
							{{form.tipo}}
						</div>
						<div class="form-group col-md-4">
							<label for="{{form.nro.label}}"><strong>{{form.nro.label}}</strong></label>
							{{form.nro}}
						</div>
						<div class="form-group col-md-4">
							<label for="{{form.fecha.label}}"><strong>{{form.fecha.label}}</strong></label>
							{{ form.fecha }} <!-- |date:'%d-%m-%Y' -->
						</div>
					</div>

					<div class="form-row">
						<div class="form-group col-md-4">
							<label for="{{form.recurrente.label}}"><strong>{{form.recurrente.label}}</strong></label>
							{{form.recurrente}}
						</div>
						<div class="form-group col-md-4">
							<label for="{{form.tecnico.label}}"><strong>{{form.tecnico.label}}</strong></label>
							{{form.tecnico}}
						</div>
						<div class="form-group col-md-4">
							<label for="{{form.estado.label}}"><strong>{{form.estado.label}}</strong></label>
							{{form.estado}}
						</div>
					</div>

		<br>


		<div class="card shadow mb-12">
			<a href="#collapse_motivo" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapse_motivo">
                <h6 class="m-0 font-weight-bold text-primary">Motivo(s)</h6>
            </a>
			<div class="collapse show" id="collapse_motivo">
             	<div class="card-body">
						<div class="form-group col-md-12">
							<label for="{{form.motivo.label}}"><strong>{{form.motivo.label}}</strong></label>
							<br>
							{% for checkbox in form.motivo %}
								<label class="form-check-label" style="padding: 10px;">
								   {{checkbox.tag}}{{checkbox.choice_label}}
							    </label>
							{% endfor %}
						</div>
				</div> 
			</div>
		</div>
		<br>

	<br>
	<br>

		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="{{form.imagen.label}}"><strong>{{form.imagen.label}}</strong></label>
				{{form.imagen}}
			</div>
			<div class="form-group col-md-12">
				<label for="{{form.observacion.label}}"><strong>{{form.observacion.label}}</strong></label>
				{{form.observacion}}
			</div>
		</div>

		<div class="form-row">
			<div class="form-group col-md-4">
				<label for="{{form.activo.label}}"><strong>{{form.activo.label}}</strong></label>
				<input type="text" name="activo" class="form-control" id="disabledTextInput" readonly="readonly" placeholder="{{ form.activo|yesno:"SI,NO" }}">
			</div>
			<div class="form-group col-md-4">
				<label for="{{form.modificado.label}}"><strong>{{form.modificado.label}}</strong></label>
				<input type="text" name="modificado" class="form-control" id="disabledTextInput" readonly="readonly" placeholder="{{ form.modificado }}
			</div>
			<div class="form-group col-md-4">
				<label for="{{form.creado_por.label}}"><strong>{{form.creado_por.label}}</strong></label>

				{% if form.creado_por  %}
					{% if form.creado_por.value == 1 %}
						<input type="text" name="creado_por" class="form-control" id="disabledTextInput" readonly="readonly" placeholder="Alvaro">
					{% endif %}
					{% if form.creado_por.value == 4 %}
						<input type="text" name="creado_por" class="form-control" id="disabledTextInput" readonly="readonly" placeholder="Maggie">
					{% endif %}
				{% endif %}

				{% if form.creado_por.value is None %}
					<input type="text" name="creado_por" class="form-control" id="disabledTextInput" readonly="readonly" placeholder="{{user.username}}">
				{% endif %}
				

			</div>
		</div>
		
		<br>
		<button type="submit" class="btn btn-primary">Guardar</button>
		<a class="btn btn-secondary" href="{% url 'documento_list' %}" style="color:white">Cancelar</a>

		<!-- {{form.as_p}} -->
		</div>
		</div>

	</form>

{% endblock %}



{% block footer %}
	<br>
{% endblock %}

templates/documento_list.html
{% extends 'base.html' %}

{% block content %}
	{% if object_list %}
       <div class="card shadow mb-4">
           <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Listado de Documentos</h6>
           </div>
         
           <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  	<thead>
					  <tr>
					  	<th scope="col">Tipo</th>
				      	<th scope="col">Nro</th>
				      	<th scope="col">Fecha</th>
				      	<th scope="col">Recurrente</th>
				      	<th scope="col">Motivo(s)</th>
				      	<th scope="col">Estado</th>
				      	<th scope="col">Acciones</th>
				      </tr>
					</thead>
			  		<tbody>
					  	{% for doc in object_list %}
							{% if doc.estado.nombre == 'Vencido' %}
								<tr class="table-danger">
							{% elif doc.estado.nombre == 'Pendiente'%}
								<tr class="table-warning">
							{% elif doc.estado.nombre == 'Informado'%}
								<tr class="table-success">
							{% endif %}
								{% if doc.tipo == 1 %}
									  <td><p>Expediente</p></td>
									{% elif doc.tipo == 2 %}
										<td><p>Nota</p></td>
									{% elif doc.tipo == 3 %}
										<td><p>Memo</p></td>
									{% elif doc.tipo == 4 %}
										<td><p>Oficio</p></td>
									{% elif doc.tipo == 5 %}
										<td><p>Formulario</p></td>
								{% endif %}
							      <td><p>{{doc.nro}}</p></td>
							      <td><p>{{doc.fecha}}</p></td>
							      <td><p>{{doc.recurrente.nombre}}</p></td>
							      <td><p>{{doc.motivo.all|join:", " }}</p></td>
							      <td><p><strong>{{doc.estado.nombre}}</strong></p></td>
							      <td>
									    <a class="btn btn-info btn-circle btn-sm" href="{% url 'documento_edit' doc.id %}"> 
									    	<i class="fas fa-info-circle"></i>
									    </a>
									   	<a class="btn btn-danger btn-circle btn-sm" href="{% url 'documento_delete' doc.id %}"> 
											<i class="fas fa-trash"></i>
									   	</a>
							    </tr>
							
						{% endfor %}
			  		</tbody>
				</table> 
              </div>
            </div>
          </div>
	
	<br>
	{% else %}
		<h3>No hay documentaciones para mostrar</h3>
	{% endif %}
{% endblock %}

templates/espacios_reservados.html
{% extends 'base.html' %}
{% load static %}

<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" media="all">

{% block content %}
	{% if espacios_dic %}
	
		<div class="row">
		<h3>Espacios Reservados</h3>
			<!-- ESPACIOS -->
			<div class="col-md-12">
				<div class="table-responsive">
					<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
						<thead class="thead-dark">
						  <tr>
						      <th scope="col">Informe</th>
						      <th scope="col">Expediente</th>
						      <th scope="col">Recurrente</th>
						      <th scope="col">Calle Principal</th>
						      <th scope="col">Entre Calle</th>
						      <th scope="col">Y Calle</th>
						      <th scope="col">Espacios</th>
						    </tr>
						</thead>
				  		<tbody>
						  	{% for key, value in espacios_dic.items %}
							  	<tr>
									<td> {{value.1}} </td>
									<td> {{value.13}} </td>
									<td> {{value.11}} </td>
									<td> {{value.3|title}} </td>
									<td> {{value.5|title}} </td>
									<td> {{value.7|title}} </td>
									<td> {{value.9}} </td>
								</tr>
							{% endfor %}
						</tbody>
					</table> 
				</div>
			</div>


		</div>

	{% else %}
		<h3>Nandi vera</h3>
	{% endif %}



{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block content %}

	<div class="jumbotron">
	  <h1 class="display-4">Saludos {{user.username}}!</h1>
	  <p class="lead">Esta aplicación fue desarrollada para soporte del Departamento de Ingeniería de Tráfico</p>
	  <hr class="my-4">
	  <p>Ideada para pretaciones de tareas repetitivas, consultas, estadísticas y reportes, encontrarás los menús en la sección izquierda de la página</p>
	  <p class="lead">
	    <a class="btn btn-primary btn-lg" href=" {% url 'panel' %} " role="button">Entendido...</a>
	  </p>
	</div>

{% endblock %}

templates/recurrentes.html
{% extends 'base.html' %}
{% load static %}

<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" media="all">

{% block content %}
	{% if recurrentes_dic %}
	
		<div class="row">
		<h3>Recurrentes</h3>
			<!-- ESPACIOS -->
			<div class="col-md-12">
				<div class="table-responsive">
					<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
						<thead class="thead-dark">
						  <tr>
						      <th scope="col">Id</th>
						      <th scope="col">Nombre</th>
						      <th scope="col">Apellido</th>
						      <th scope="col">Email</th>
						      <th scope="col">Telefono</th>
						      <th scope="col">RUC</th>
						      <th scope="col">RMC</th>
						      {% if perms.ingenieria.change_recurrente %}
						      	<th scope="col">Acciones</th>
						      {% endif %}
						    </tr>
						</thead>
				  		<tbody>
						  	{% for key, value in recurrentes_dic.items %}
							  	<tr>
									<td> {{value.1}} </td>
									<td> {{value.3}} </td>
									<td> {{value.5|title}} </td>
									<td> {{value.7}} </td>
									<td> {{value.9}} </td>
									<td> {{value.11}} </td>
									<td> {{value.13}} </td>
									{% if perms.ingenieria.change_recurrente %}
										<td> Botones </td>
									{% endif %}
								</tr>
							{% endfor %}
						</tbody>
					</table> 
				</div>
			</div>


		</div>

<!-- {% for key, value in calles_dic.items %}
	<p>{{key}}, {{value}}</p>
{% endfor %} -->


	{% else %}
		<h3>Nandi vera</h3>
	{% endif %}



{% endblock %}

templates/tablas.html
{% extends 'base.html' %}
{% load static %}

<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" media="all">

{% block content %}
	{% if data %}
		<h2>Reportes - Resúmen General</h2>

	<!-- FILA 1 -->
		<div class="row">

		<!-- DOCUMENTOS TIPOS -->
			<div class="col-xs-6 col-md-4">
				<table class="table">
				  <thead class="thead-dark">
				    <tr>
				      <th scope="col">Documentos</th>
				      <th scope="col">Cantidad</th>
				    </tr>
				  </thead>
				  <tbody>
				    <tr>
				      <td>Expedientes</td>
				      <td>{{data.expediente}}</td>
				    </tr>
				      <td>Notas</td>
				      <td>{{data.nota}}</td>
				    </tr>
				      <td>Memos</td>
				      <td>{{data.memo}}</td>
				    </tr>
				      <td>Oficios</td>
				      <td>{{data.oficio}}</td>
				    </tr>
				      <td>Formularios</td>
				      <td>{{data.formulario}}</td>
				    </tr>
				  </tbody>
				</table>
			</div>

		<!-- DOCUMENTOS ESTADOS -->
			<div class="col-xs-6 col-md-4">
				<table class="table">
				  <thead class="thead-dark">
				    <tr>
				      <th scope="col">Estado</th>
				      <th scope="col">Informes</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for key, value in estados_dic.items %}
						{% if key == 'Pendiente' %}
							<tr class="table-warning">
						{% elif key == 'Informado'  %}
							<tr class="table-success">
						{% elif key == 'Vencido'  %}
							<tr class="table-danger">
						{% endif %}
								<td> {{key}} </td>
						    	<td> {{value}} </td>
				   			</tr>
				   	{% endfor %}
				  </tbody>
				</table>
			</div>
		</div>    
		

<br>
<br>

		<!-- FILA 2 -->
		<div class="row">

			<!-- MOTIVOS -->
			<div class="col-xs-6 col-md-4">
				<table class="table">
				  <thead class="thead-dark">
				    <tr>
				      <th scope="col">Motivo</th>
				      <th scope="col">Informes</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for key, value in motivos_dic.items %}
					  	<tr>
							<td> {{key}} </td>
							<td> {{value}} </td>
						</tr>
					{% endfor %}
				  </tbody>
				</table>
			</div>
			
			<!-- TECNICOS -->
			<div class="col-xs-6 col-md-4">
				<table class="table">
				  <thead class="thead-dark">
				    <tr>
				      <th scope="col">Técnico</th>
				      <th scope="col">Informes</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for key, value in tecnicos_dic.items %}
					  	<tr>
							<td> {{key}} </td>
							<td> {{value}} </td>
						</tr>
					{% endfor %}
				  </tbody>
				</table>
			</div>
		</div>

		

<br>
<br>

	{% else %}
		<h3>Nandi vera</h3>
	{% endif %}



{% endblock %}